### ISSUE TITLE
Why "setEnergyOfReference 159 keV" ? 

### ISSUE THREAD

**Issue by HeConnor** [BenAuer2021/Simulation-Of-Nuclear-Medicine-Imaging-Systems-Scintigraphy-SPECT#1]
Hello,

   In "GATE_MACROS_Jaszczak"-> "Brightview_Main_LEHR_Oz_Jas.mac", I have a question about “`/gate/digitizer/Singles/blurring/linear/setEnergyOfReference 159.0 keV`” in **Digiter** in the tutorial.

   Why is it set to 159 keV, instead of 140.5 keV (Tc-99m Mono-Energy)？

Thank you for your help,

Best regards

Connor

**Comment by BenAuer2021** [comment]
Hi Connor,

It is the energy of reference for the energy resolution. You can also set it for Tc (9-10% typically at 140 keV). Gate calculates the energy resolution for the different energy considered in the simulation (eg scatter) in any case.

Ben

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Connor_He ***@***.***>
Sent: Sunday, April 7, 2024 5:01:04 AM
To: BenAuer2021/Simulation-Of-Nuclear-Medicine-Imaging-Systems-Scintigraphy-SPECT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [BenAuer2021/Simulation-Of-Nuclear-Medicine-Imaging-Systems-Scintigraphy-SPECT] Why "setEnergyOfReference 159 keV" ? (Issue #1)


Hello,

In "GATE_MACROS_Jaszczak"-> "Brightview_Main_LEHR_Oz_Jas.mac", I have a question about “/gate/digitizer/Singles/blurring/linear/setEnergyOfReference 159.0 keV” in Digiter in the tutorial.

Why is it set to 159 keV, instead of 140.5 keV (Tc-99m Mono-Energy)？

Thank you for your help,

Best regards

Connor
